### ISSUE TITLE
Provided Twitter dataset parsing error

### ISSUE THREAD

**Issue by michalilski** [behavioral-ds/evently#15]
Parsing the provided  Twitter data with `parse_raw_tweets_to_cascades` function throws: `Error in retweet_id[-1] - retweet_id[-length(retweet_id)]: non-numeric argument to binary operator` in line:
https://github.com/behavioral-ds/evently/blob/9be4daa8b8dcbc7f0f4d585c954f7f033b984a33/R/tweet.R#L143

This error disappears when I exclude the records with `retweet_id` field from dataset. I think this might be caused by assigning `id_str` in line: https://github.com/behavioral-ds/evently/blob/9be4daa8b8dcbc7f0f4d585c954f7f033b984a33/R/tweet.R#L53

**Comment by janpawlowskiof** [comment]
I confirm that this error occurs

**Comment by qykong** [comment]
Hi @michalilski  and @janpawlowskiof , thanks for reporting the issue. However, I couldn't reproduce this issue from my environment (R version 3.6.1). Just wondering which R version were you using?

**Comment by michalilski** [comment]
I am using `R version 4.1.2`.
