### ISSUE TITLE
Compute likelihood for observation times shorter than the last event

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/evently#2]
The `get_hawkes_neg_likelihood_value` can be used to compute the likelihood of an event sequence (given in `model$data`) until the observation time. However, if I set the observation time less than the last even in the series, it appears that the function computes the log-likelihood until the last event.

When computing the holdout log-likelihood for the testing part of a sequence, one typically needs to subtract the training likelihood from the total likelihood. The training likelihood has the observation time before the last event in the sequence. The total likelihood may have the observation time larger than the last event (say if I continue to observe the process after that last event).

Can that be achieved with this function?

**Comment by qykong** [comment]
Hi Andrei, currently this function only computes on what's given which means, for observation time before last event, one needs to slice the event sequence before giving the sequence to the function. but it makes sense to change the function to deal with this. I'll update the function.
