### ISSUE TITLE
Documentation link in the README

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/evently#4]
I noticed that the README does not have a link to the documentation. Is it possible to link that?

**Comment by qykong** [comment]
Hi andrei, could you please specify which documentation are you referring to?

**Comment by qykong** [comment]
I've added this link to the README: https://www.behavioral-ds.ml/evently/

**Comment by andrei-rizoiu** [comment]
Yep, that's what I meant! However, I didn't realize that was the documentation.
Can we get a section before acknowledgements to clearly state that "Please consult the package documentation <link> for more details and tutorials".

**Comment by qykong** [comment]
sure, i'll add that
