### ISSUE TITLE
The time is not strictly increasing

### ISSUE THREAD

**Issue by nurek-mateusz** [behavioral-ds/evently#5]
Hi, I found a potential bug in Evently causing the following error message: "'Something went wrong! The time is not strictly increasing.'".

My dataframe of events history looks like this:
```
##   magnitude      time
## 1         1 0.0000000
## 2         1 0.5941959
## 3         1 1.4712411
## 4         1 1.4712411
## 5         1 1.4712455
```

In the file `hawkes.R`, in the function `offset_same_time`, a random number is added on line 218, which can sometimes disturb the increasing order of data:
`history$time[i] <- history$time[i-1] + runif(1, 0, 1e-5)`

In my case, I got:
```
##   magnitude      time
## 1         1 0.0000000
## 2         1 0.5941959
## 3         1 1.4712411
## 4         1 1.4712470
## 5         1 1.4712455
```
The order between 4 and 5 is disturbed.

**Comment by qykong** [comment]
Hi, thanks for the bug report. I'll look into this 😁
