### ISSUE TITLE
Implement history cut-off to be able to fit large sequences

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/evently#8]
Currently, evently accounts for all events when fitting. This means we cannot fit beyond 2-3K events. Could we implement a cutoff strategy to only account for one of:

* the last XX events
* the last YY time units
* only the last event whose intensity contribution is > ZZ epsilon

**Comment by qykong** [comment]
WIP:

- [X] the last XX events
- [ ] the last YY time units
- [ ] only the last event whose intensity contribution is > ZZ epsilon

The last point might not be implemented as it involves conditional computation during optimization in AMPL, i.e., discard events based on the intensity values when evaluating LL values. However, this isn't possible for AMPL.

**Comment by andrei-rizoiu** [comment]
OK, that already seems usable enough. Can we get some examples of how to use this in the README / doc and close the ticket?
